spring.application.name=paf_25l

server.port=8080
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=
spring.data.redis.password=

redis.topic1=todo
redis.topic2=student


spring.datasource.url=jdbc:mysql://localhost:3306
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password==${MYSQL_PASSWORD}